# Generated by Django 5.1.7 on 2025-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renter", "0006_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bike",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
