# Generated by Django 5.1.7 on 2025-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renter", "0007_bike_price_bike_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="price",
            field=models.CharField(max_length=10),
        ),
    ]
