# Generated by Django 5.1.7 on 2025-04-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renter", "0008_alter_bike_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="bike_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="renter.bike",
            ),
        ),
    ]
