# Generated by Django 5.1.7 on 2025-08-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renter", "0009_alter_booking_bike_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="bookings_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bike",
            name="category",
            field=models.CharField(
                choices=[
                    ("road", "Road Bike 🚴"),
                    ("mountain", "Mountain Bike ⛰️"),
                    ("electric", "Electric Bike ⚡"),
                ],
                default="road",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
