# Generated by Django 5.1.7 on 2025-08-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renter", "0010_bike_bookings_count_bike_category_bike_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="desc",
            field=models.TextField(max_length=300),
        ),
    ]
