# Generated by Django 5.1.7 on 2025-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("renter", "0011_alter_bike_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="desc",
            field=models.TextField(),
        ),
    ]
